sudo: required

language: python

python:
  - 2.7

services:
  - mysql

before_install:
  - wget http://files.vlabs.ac.in/downloads/emacs.tar.gz
  - tar -xvzf emacs.tar.gz
  - cp -r emacs /home/travis/
  - git clone https://github.com/ksripathi/test-project1
  - cd test-project1
  - make
  - mysql -e 'CREATE DATABASE myapp_test;'
  - mysql -e 'show databases;'

install: 
  - sudo apt-get update -y
  
script:
  - python tests.py

after_success:
  - cat /etc/issue

