sudo: false

language: python

python:
  - 2.7

install: true
  
script:
  - python tests.py

after_success:
  - ls
notifications:
  email:
    recipients:
      - kammari.sripathi@gmail.com
  
    on_success: always # default: change
    on_failure: always # default: always

