sudo: required

env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=7

language: python

python:
  - 2.7

install: true
  
script:
  - python tests.py

after_success:
  - cat /etc/issue

