sudo: required

language: python

python:
  - 2.7

services:
  - mysql

before_install:
  - wget http://files.vlabs.ac.in/downloads/emacs.tar.gz
  - tar -xvzf emacs.tar.gz
  - cp -r emacs /home/travis/
  - git clone https://github.com/ksripathi/test-project
  - cd test-project
  - make
  - mysql -e 'CREATE DATABASE myapp_test;'
  - mysql -e 'show databases;'
  - cd build/code/
  - export PYTHONPATH=$(pwd)
  - cd deployment
  - python setup.py install
  - python db_setup.py  

install: 
  - sudo apt-get update -y
  
script:
  - ls

after_success:
  - cat /etc/issue

