sudo: required

language: python

python:
  - 2.7

services:
  - mysql

before_install:
  - wget http://files.vlabs.ac.in/downloads/emacs.tar.gz
  - tar -xvzf emacs.tar.gz
  - cp -r emacs /home/travis/
  - git clone https://github.com/ksripathi/test-project
  - cd test-project
  - make
  - mysql -e 'CREATE DATABASE lds;'
  - mysql -e 'show databases;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - cd build/code/
  - export PYTHONPATH=$(pwd)
  - cd deployment
  - pip install oursql Flask Flask-SQLAlchemy requests flask-cors flask-testing pyyaml
  - python db_setup.py  

install: 
  - sudo apt-get update -y
  
script:
  - ls

after_success:
  - cat /etc/issue

