sudo: required

language: python

python:
  - 2.7

services:
  - mysql

before_install:

  - mysql -e 'CREATE DATABASE myapp_test;'

install: 
  - sudo apt-get update -y
  
script:
  - python tests.py

after_success:
  - cat /etc/issue

